"""add_sbommodel

Revision ID: b8e854eb3d0b
Revises: 94f52f8f9645
Create Date: 2026-08-24 22:41:40.613160
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b8e854eb3d0b"
down_revision: str | None = "94f52f8f9645"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sboms",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scan_id", sa.String(length=36), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sboms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sboms_scan_id"), ["scan_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sboms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sboms_scan_id"))

    op.drop_table("sboms")
    # ### end Alembic commands ###
